// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXqQdXiqIfU9QG28sK2TCt__F58yW1yk',
    appId: '1:65759944198:web:773352d8a7f2c216076d87',
    messagingSenderId: '65759944198',
    projectId: 'dual-money-tracker',
    authDomain: 'dual-money-tracker.firebaseapp.com',
    storageBucket: 'dual-money-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo9VQkfjVeiD7qrusvFb8vnP8rMWromJY',
    appId: '1:65759944198:android:456e97160e757b21076d87',
    messagingSenderId: '65759944198',
    projectId: 'dual-money-tracker',
    storageBucket: 'dual-money-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVKYLkOaCT4CmJ4I_75LBTmTfaKHKCzd4',
    appId: '1:65759944198:ios:26abb8662e68a0a4076d87',
    messagingSenderId: '65759944198',
    projectId: 'dual-money-tracker',
    storageBucket: 'dual-money-tracker.firebasestorage.app',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVKYLkOaCT4CmJ4I_75LBTmTfaKHKCzd4',
    appId: '1:65759944198:ios:26abb8662e68a0a4076d87',
    messagingSenderId: '65759944198',
    projectId: 'dual-money-tracker',
    storageBucket: 'dual-money-tracker.firebasestorage.app',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOXqQdXiqIfU9QG28sK2TCt__F58yW1yk',
    appId: '1:65759944198:web:142452eecfe26606076d87',
    messagingSenderId: '65759944198',
    projectId: 'dual-money-tracker',
    authDomain: 'dual-money-tracker.firebaseapp.com',
    storageBucket: 'dual-money-tracker.firebasestorage.app',
  );
}
